make_header() {
  cat <<EOF
# This file is generated by [bash-completor](https://github.com/adoyle-h/bash-completor/tree/$VERSION). Do not modify it manually.
#
# [Usage]
# Put "source $output" in your bashrc.
#
# If you want to debug the completion.
# Search '# Uncomment this line for debug' line in this file.
#
# [Update Script]
# bash-completor $ARGS
EOF

  if [[ -n ${version:-} ]]; then
    cat <<EOF
#
# [Version] $version
EOF
  fi

  if [[ -n ${license:-} ]]; then
    cat <<EOF
#
# [License] $license
EOF
  fi

  if (( ${#authors[@]} > 0 )); then
    cat <<EOF
#
# [Authors]
EOF

    {
      local IFS=$'\n'
      local author
      for author in "${authors[@]}"; do
        echo "# ${author}"
      done
    }
  fi

  if (( ${#maintainers[@]} > 0 )); then
    cat <<EOF
#
# [Maintainers]
EOF

    {
      local IFS=$'\n'
      local maintainer
      for maintainer in "${maintainers[@]}"; do
        echo "# ${maintainer}"
      done
    }
  fi

  if [[ -n ${description:-} ]]; then
    cat <<EOF
#
# [Description]
# ${description}
EOF
  fi

  if [[ -n ${notice:-} ]]; then
    cat <<EOF
#
# [Notice]
# ${notice}
EOF
  fi

  cat <<EOF

# shellcheck disable=2207
# editorconfig-checker-disable
EOF
}
