name: release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build
        run: make build VERSION=${{github.ref_name}}

      - name: For file integrity
        run: make md5

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
