name: release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make build VERSION=${{github.ref_name}}

      - name: For file integrity
        run: make md5

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body: Please read the [CHANGELOG](https://github.com/${{github.repository}}/blob/master/CHANGELOG.md#${{github.ref_name}}).
